---
- name: Ensure NFS basic utilites are installed.
  apt:
    name:
      - nfs-common
    state: present

- name: Ensure NFS server utilites are installed.
  apt:
    name:
      - nfs-kernel-server
    state: present
  when: nfs_exports|length
