---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: rhel.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure directories to export exist
  file:
    path: "{{ item.strip().split()[0] }}"
    state: directory
  with_items: "{{ nfs_exports }}"

- name: Ensure directories to mount exist
  file:
    path: "{{ item.strip().split()[0] }}"
    state: directory
  with_items: "{{ nfs_mounts }}"

- name: Copy exports file.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: Reload NFS
  when: nfs_exports|length

- name: Ensure nfs is running.
  service: "name={{ nfs_server_daemon }} state=started enabled=yes"
  when: nfs_exports|length

- name: Mount nfs directories
  mount:
    src: "{{ item.strip().split()[1] }}"
    path: "{{ item.strip().split()[0] }}"
    state: mounted
  with_items: "{{ nfs_mounts }}"
