---
- name: Ensure NFS utilities are installed.
  package: name=nfs-utils state=present

- name: Ensure rpcbind is running as configured.
  service:
    name: rpcbind
    state: "started"
    enabled: true
